# Generated by Django 5.1.4 on 2025-01-03 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Порода собаки')),
                ('size', models.CharField(choices=[('TINY', 'Крошечная'), ('SMALL', 'Маленькая'), ('MEDIUM', 'Средняя'), ('LARGE', 'Большая')], max_length=8, verbose_name='Размер собаки')),
                ('friendliness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Дружелюбность собаки')),
                ('trainability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Способность к тренировкам')),
                ('shedding_amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Интенсивность линьки')),
                ('exercise_needs', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Потребность в упражнениях')),
            ],
            options={
                'verbose_name': 'Порода собаки',
                'verbose_name_plural': 'Породы собак',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Кличка собаки')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст собаки')),
                ('gender', models.CharField(choices=[('MALE', 'Самец'), ('FEMALE', 'Самка')], max_length=8, verbose_name='Пол собаки')),
                ('color', models.CharField(max_length=128, verbose_name='Окрас собаки')),
                ('favourite_food', models.CharField(max_length=128, verbose_name='Любимая еда')),
                ('favourite_toy', models.CharField(max_length=128, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.breed', verbose_name='Порода собаки')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ('name',),
            },
        ),
    ]
